In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3,1) # 3 dimantion
new=arr.reshape(2,3) # 2 dimantion
newarr1=arr.reshape(2,3,1).base
new1=arr.reshape(2,-1) # if you are enter one parameter as -1 then it will set own.
new2=arr.reshape(-1,3)
print(newarr)
print("-"*50)
print(new)
print("-"*50)
print(newarr1) # when you have to check base after modification then use
print("-"*50)
print(new1)
print("-"*50)
print(new2)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[1 2 3 4 5 6]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for x in arr:
    print(x)

1
2
3
4
5
6


In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2 dimention
for i in arr:
    print(i)
print("-"*50)
for i in arr:
    for j in i:
        print(j)

[1 2 3 4]
[5 6 7 8]
--------------------------------------------------
1
2
3
4
5
6
7
8


In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 diamention
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [15]:
# nditer(n dimention iterator) : it will fatch until last element in single loop.

In [13]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) # 2 dimention
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [14]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 diamention
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(arr[0:1,::2]): # If you want to get specific charactor then use like this.
    print(i)

1
3


In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(arr[:,::2]): 
    print(i)

1
3
5
7


# Built-in Functions

### 1. concatenate()

In [21]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.array([7,8,9])
arr=np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [22]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2))
print(arr)

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [28]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2),axis=0) # bydefult axis is 0.
print(arr)

[[1 2]
 [5 6]
 [3 4]
 [7 8]]


In [27]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [29]:
arr1=np.array([[1,2],[5,6]])
arr2=np.array([[3,4],[7,8],[9,10]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [36]:
arr1=np.array([[[1,2],[5,6]],[[3,4],[7,8]]])
arr2=np.array([[[10,20],[50,60]],[[30,40],[70,80]]])
arr=np.concatenate((arr1,arr2),axis=0) # bydefult axis is 0.
print(arr)

[[[ 1  2]
  [ 5  6]]

 [[ 3  4]
  [ 7  8]]

 [[10 20]
  [50 60]]

 [[30 40]
  [70 80]]]


In [38]:
arr1=np.array([[[1,2],[5,6]],[[3,4],[7,8]]])
arr2=np.array([[[10,20],[50,60]],[[30,40],[70,80]]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[[ 1  2]
  [ 5  6]
  [10 20]
  [50 60]]

 [[ 3  4]
  [ 7  8]
  [30 40]
  [70 80]]]


### 2. split()

In [30]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,4)
print(newarr)

[array([1]), array([2]), array([3]), array([4])]


In [31]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,3)
print(newarr)

[array([1, 2]), array([3]), array([4])]


In [32]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,2)
print(newarr)

[array([1, 2]), array([3, 4])]


In [33]:
arr1=np.array([1,2,3,4])
newarr=np.array_split(arr1,5)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32)]


In [34]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [35]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8]])
newarr=np.array_split(arr1,4,axis=0)
print(newarr)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [40]:
arr1=np.array([[[1,2],[5,6]],[[3,4],[7,8]]])
newarr=np.array_split(arr1,4,axis=0)
print(newarr)

[array([[[1, 2],
        [5, 6]]]), array([[[3, 4],
        [7, 8]]]), array([], shape=(0, 2, 2), dtype=int32), array([], shape=(0, 2, 2), dtype=int32)]


In [41]:
arr1=np.array([[[1,2],[5,6]],[[3,4],[7,8]]])
newarr=np.array_split(arr1,4,axis=1)
print(newarr)

[array([[[1, 2]],

       [[3, 4]]]), array([[[5, 6]],

       [[7, 8]]]), array([], shape=(2, 0, 2), dtype=int32), array([], shape=(2, 0, 2), dtype=int32)]


### 3.where()

In [43]:
arr1=np.array([1,2,3,4,5,6,4,2,3])
x=np.where(arr1==4)
print(x)
y=np.where(arr1%2==0) # return index
print(y)

(array([3, 6], dtype=int64),)
(array([1, 3, 5, 6, 7], dtype=int64),)


In [45]:
arr1=np.array([[1,2],[3,4],[5,6],[4,8]]) # it will give ans in dimential form
#                     0 1         0 1
#                      1           3
x=np.where(arr1==4)
print(x)

(array([1, 3], dtype=int64), array([1, 0], dtype=int64))


In [47]:
arr1=np.array([[[1,2],[3,4]],[[5,6],[4,8]]])
#                      0 1           0 1
#                       1             1
#                    0             1
x=np.where(arr1==4)
print(x)

(array([0, 1], dtype=int64), array([1, 1], dtype=int64), array([1, 0], dtype=int64))


In [48]:
arr1=np.array([[[1,2],[3,4]],[[4,6],[4,8]]])
x=np.where(arr1==4)
print(x)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([1, 0, 0], dtype=int64))


In [49]:
arr1=np.array([[[1,4],[3,4]],[[4,6],[4,8]]])
x=np.where(arr1==4)
print(x)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64), array([1, 1, 0, 0], dtype=int64))


In [50]:
arr1=np.array([[[1,4],[3,4,4]],[[4,6],[4,8]]])
x=np.where(arr1==4)
print(x)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.

### 4. sort()

In [52]:
arr1=np.array([1,2,3,4,5,6,4,2,3])
print(np.sort(arr1)) # here defult axis is -1

[1 2 2 3 3 4 4 5 6]


In [53]:
arr2=np.array(["apple","cherry","banana"])
print(np.sort(arr2))

['apple' 'banana' 'cherry']


In [54]:
arr3=np.array([True,False,True])
print(np.sort(arr3))

[False  True  True]


In [55]:
arr=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [57]:
arr=np.array([[3,4,2],[1,7,3],[4,2,5]])
print(np.sort(arr,axis=0))

[[1 2 2]
 [3 4 3]
 [4 7 5]]


In [59]:
arr=np.array([[3,4,2],[1,7,3],[4,2,5]]) # same as bydefult
print(np.sort(arr,axis=1))

[[2 3 4]
 [1 3 7]
 [2 4 5]]


In [60]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,7,4]]])
print(np.sort(arr1))

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 7 9]]]


In [61]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,7,4]]])
print(np.sort(arr1,axis=0))

[[[3 2 2]
  [7 7 3]]

 [[6 7 8]
  [9 9 4]]]


In [62]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,7,4]]])
print(np.sort(arr1,axis=1))

[[[3 2 3]
  [7 9 8]]

 [[6 7 2]
  [9 7 4]]]


In [64]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,7,4]]])
print(np.sort(arr1,axis=2)) # same as normal 

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 7 9]]]


In [65]:
arr1=np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,7,4]]])
print(np.sort(arr1,axis=-1))

[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 7 9]]]


# Random Modul

### 1. randint()

In [67]:
from numpy import random
x=random.randint(100) # by defult start point is 0 . [0,100) 
print(x)

72


In [69]:
from numpy import random
x=random.randint(10,100) # any number between. [10,99] 
print(x)

87


In [71]:
from numpy import random
x=random.randint(10,100,size=(5)) # genrate array by size . [10,99]
print(x)

[28 45 35 77 74]


In [74]:
from numpy import random
x=random.randint(1,100,size=(3,5))  
print(x)

[[ 5 90 56  2  3]
 [54 34 21  8 11]
 [31 26  2 97 56]]


In [75]:
from numpy import random
x=random.randint(1,100,size=(3,5,2))  
print(x)

[[[51 34]
  [25 26]
  [55 79]
  [51 23]
  [ 9 50]]

 [[28 28]
  [18 19]
  [18 12]
  [79 83]
  [14  8]]

 [[16  3]
  [ 2 64]
  [24 83]
  [93 13]
  [13 50]]]


### 2. rand() 

In [77]:
x=random.rand() # generate number between 0 to 1.
print(x)

0.05343035652975403


In [79]:
x=random.rand(5) # generate number between 0 to 1.with array that size is 5.
print(x)

[0.44842948 0.83042916 0.4396939  0.67563137 0.63861861]


In [80]:
x=random.rand(3,5) 
print(x)

[[0.24819719 0.27900768 0.12771383 0.60349382 0.8778302 ]
 [0.5073228  0.35132162 0.96434365 0.99158744 0.22706729]
 [0.99324363 0.5519004  0.26650212 0.48546199 0.24739326]]


### 3. choice()

In [85]:
x=random.choice([1,3,5,7,9]) # choice any number from that list
print(x)

7


In [87]:
x=random.choice([1,3,5,7,9],size=5) # make array by size 5.choice can be multiple.
print(x)

[1 5 7 1 3]


In [89]:
x=random.choice([1,3,5,7,9],size=(3,5))
print(x)

[[7 1 1 9 9]
 [7 1 9 7 9]
 [3 1 7 7 7]]


In [90]:
x=random.choice([1,3,5,7,9],size=3,5)
print(x)

SyntaxError: positional argument follows keyword argument (<ipython-input-90-f3631b6fa84d>, line 1)

# WAP to make number gasing name.attempt is 7

In [102]:
from numpy import random
x=random.randint(100)
i=0
while(i<7):
    print("-"*50)
    print("You have ",7-i," Attempt.")
    n=int(input("Enter Number :"))
    if n==x:
        print("🎉🎉------------Congratulation----------🎉🎉")
        print("You Win😎")
        print("You guess correct number.")
        break
    if n>x:
        print("Number is Lower then your Number.")
    else:
        print("Number is Greater then your Number.")
    i+=1
    print("-"*50)
else:
    print("----game over----")
    print("You can not able to guess number.😌")
    print("Correct Number is :",x)

--------------------------------------------------
You have  7  Attempt.
Enter Number :50
Number is Greater then your Number.
--------------------------------------------------
--------------------------------------------------
You have  6  Attempt.
Enter Number :80
Number is Greater then your Number.
--------------------------------------------------
--------------------------------------------------
You have  5  Attempt.
Enter Number :90
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  4  Attempt.
Enter Number :95
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  3  Attempt.
Enter Number :70
Number is Greater then your Number.
--------------------------------------------------
--------------------------------------------------
You have  2  Attempt.
Enter Number :25
Number is Greater then your N

In [101]:
from numpy import random
x=random.randint(100)
i=0
while(i<7):
    print("-"*50)
    print("You have ",7-i," Attempt.")
    n=int(input("Enter Number :"))
    if n==x:
        print("🎉🎉------------Congratulation----------🎉🎉")
        print("You Win😎")
        print("You guess correct number.")
        break
    if n>x:
        print("Number is Lower then your Number.")
    else:
        print("Number is Greater then your Number.")
    i+=1
    print("-"*50)
else:
    print("----game over----")
    print("You can not able to guess number.😌")
    print("Correct Number is :",x)

--------------------------------------------------
You have  7  Attempt.
Enter Number :50
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  6  Attempt.
Enter Number :40
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  5  Attempt.
Enter Number :25
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  4  Attempt.
Enter Number :15
Number is Lower then your Number.
--------------------------------------------------
--------------------------------------------------
You have  3  Attempt.
Enter Number :10
Number is Greater then your Number.
--------------------------------------------------
--------------------------------------------------
You have  2  Attempt.
Enter Number :12
Number is Lower then your Number.