# Bill
       cashpayment(Bill)     use of constructors only
       checkpayment(Bill)    no method implitation
 HOD 5000
 RAM 2000
 Printer 6000
 Pendrive 800

In [3]:
class Bill:
    print("-"*50)
    d={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
    total=0
    for i,j in d.items():
        print(i," ",j)
        y=input("You want This Item ? (Y/N)")
        if y.lower()=="y":
            q=int(input("How many Quntity ?"))
            total+=j*q
        elif y.lower()=="n":
            pass
        else:
            print("Please Enter Valid Charecter.")
    def __init__(self):
        print("-"*50)
        print("1. Cash Payment")
        print("2. Check Payment")
        n=int(input("Enter Method (1 or 2) :"))
        if n==1:
            b=cashPayment()
        elif n==2:
            b=checkPayment()
        else:
            print("Please Enter Valid method Number.")
class cashPayment(Bill):
    def __init__(self):
        print("-"*50)
        print("Payment Method is cash.")
        print("Total Amount to Pay :",Bill.total)
        t=Bill.total
        t2000=t//2000
        t500=(t%2000)//500
        t200=((t%2000)%500)//200
        t100=(((t%2000)%500)%200)//100
        t50=((((t%2000)%500)%200)%100)//50
        t20=(((((t%2000)%500)%200)%100)%50)//20
        t10=((((((t%2000)%500)%200)%100)%50)%20)//10
        t=((((((t%2000)%500)%200)%100)%50)%20)%10
        if t2000!=0:
            print("2000 Notes :",t2000)
        if t500!=0:
            print("500 Notes :",t500)
        if t200!=0:
            print("200 Notes :",t200)
        if t100!=0:
            print("100 Notes :",t100)
        if t50!=0:
            print("50 Notes :",t50)
        if t20!=0:
            print("20 Notes :",t20)
        if t10!=0:
            print("10 Notes :",t10)
        if t!=0:
            print("Chiller :",t)
class checkPayment(Bill):
    def __init__(self):
        print("-"*50)
        print("Payment Method is Check.")
        print("Total Amount to Pay :",Bill.total)
        an=int(input("Enter Account No :"))
        bn=input("Enter Bank Name :")
        print("-----Check Details-----")
        print("Account No : ",an)
        print("Bank Name :",bn)
B=Bill()

--------------------------------------------------
HDD   5000
You want This Item ? (Y/N)y
How many Quntity ?1
RAM   2000
You want This Item ? (Y/N)y
How many Quntity ?2
Printer   6000
You want This Item ? (Y/N)n
Pendrive   800
You want This Item ? (Y/N)y
How many Quntity ?4
--------------------------------------------------
1. Cash Payment
2. Check Payment
Enter Method (1 or 2) :2
--------------------------------------------------
Payment Method is Check.
Total Amount to Pay : 12200
Enter Account No :123456
Enter Bank Name :SBI
-----Check Details-----
Account No :  123456
Bank Name : SBI


In [7]:
class Bill:
    print("-"*50)
    d={"HDD":5000,"RAM":2000,"Printer":6000,"Pendrive":800}
    total=0
    for i,j in d.items():
        print(i," ",j)
        y=input("You want This Item ? (Y/N)")
        if y.lower()=="y":
            q=int(input("How many Quntity ?"))
            total+=j*q
        elif y.lower()=="n":
            pass
        else:
            print("Please Enter Valid Charecter.")
    def __init__(self):
        print("-"*50)
        print("1. Cash Payment")
        print("2. Check Payment")
        n=int(input("Enter Method (1 or 2) :"))
        if n==1:
            b=cashPayment()
        elif n==2:
            b=checkPayment()
        else:
            print("Please Enter Valid method Number.")
class cashPayment(Bill):
    def __init__(self):
        print("-"*50)
        print("Payment Method is cash.")
        print("Total Amount to Pay :",Bill.total)
        t=Bill.total
#         t2000=t//2000
#         t500=(t%2000)//500
#         t200=((t%2000)%500)//200
#         t100=(((t%2000)%500)%200)//100
#         t50=((((t%2000)%500)%200)%100)//50
#         t20=(((((t%2000)%500)%200)%100)%50)//20
#         t10=((((((t%2000)%500)%200)%100)%50)%20)//10
#         t=((((((t%2000)%500)%200)%100)%50)%20)%10
#         if t2000!=0:
#             print("2000 Notes :",t2000)
#         if t500!=0:
#             print("500 Notes :",t500)
#         if t200!=0:
#             print("200 Notes :",t200)
#         if t100!=0:
#             print("100 Notes :",t100)
#         if t50!=0:
#             print("50 Notes :",t50)
#         if t20!=0:
#             print("20 Notes :",t20)
#         if t10!=0:
#             print("10 Notes :",t10)
#         if t!=0:
#             print("Chiller :",t)
        note={"2000 Notes :":2000,"500 Notes :":500,"200 Notes : ":200,"100 Notes :":100,"50 Notes :":50,"20 Notes :":20,"10 Notes :":10}
        for i,j in note.items():
            if t>=j:
                print(i," ",t//j)
                t=t%j
class checkPayment(Bill):
    def __init__(self):
        print("-"*50)
        print("Payment Method is Check.")
        print("Total Amount to Pay :",Bill.total)
        an=int(input("Enter Account No :"))
        bn=input("Enter Bank Name :")
        print("-----Check Details-----")
        print("Account No : ",an)
        print("Bank Name :",bn)
B=Bill()

--------------------------------------------------
HDD   5000
You want This Item ? (Y/N)y
How many Quntity ?2
RAM   2000
You want This Item ? (Y/N)y
How many Quntity ?3
Printer   6000
You want This Item ? (Y/N)y
How many Quntity ?4
Pendrive   800
You want This Item ? (Y/N)y
How many Quntity ?6
--------------------------------------------------
1. Cash Payment
2. Check Payment
Enter Method (1 or 2) :1
--------------------------------------------------
Payment Method is cash.
Total Amount to Pay : 44800
2000 Notes :   22
500 Notes :   1
200 Notes :    1
100 Notes :   1


# Numpy

In [9]:
import numpy as np
import sys
s=range(1000)
print("Size of each Element Of List in bytes :",sys.getsizeof(s))
print("Size of whole list in bytes :",sys.getsizeof(s)*len(s))

Size of each Element Of List in bytes : 48
Size of whole list in bytes : 48000


In [10]:
d=np.arange(1000)
print("Size of each Element Of Numpy array in bytes :",d.itemsize)
print("Size of whole Numpy array in bytes :",d.itemsize*d.size)

Size of each Element Of Numpy array in bytes : 4
Size of whole Numpy array in bytes : 4000


In [13]:
import numpy as np
arr=np.array(42) # 0 dimential
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5]) # 1 dimential
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[2])

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
3


In [21]:
import numpy as np
arr=np.array([[1,2,3,4,5]]) # 2 dimential
print(arr)
print(type(arr))
print(arr.ndim)
print(arr[0][2])
print(arr[0,2])

[[1 2 3 4 5]]
<class 'numpy.ndarray'>
2
3
3


In [24]:
import numpy as np
arr=np.array([[[1,2,3,4,5]]]) # 3 dimential
print(arr)
print(type(arr))
print(arr.ndim)

[[[1 2 3 4 5]]]
<class 'numpy.ndarray'>
3


In [27]:
import numpy as np
#                 0       1        0         1                      
#              -------  ------   -------  ---------
#               0 1 2   0 1 2     0 1 2   0  1  2
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimential
#             ----------------- --------------------
#                    0                   1
print(arr)
print(type(arr))
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [38]:
import numpy as np
arr=np.array([1,2,3,4,5]) # 1 dimential
print(arr[0])
print(arr[4]+arr[2])
print(arr[5]) # Error

1
8


IndexError: index 5 is out of bounds for axis 0 with size 5

In [37]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2 dimential
print(arr[1][3])

9


In [39]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimential
print(arr[0,1,1])
print(arr[1,0,2])
print(arr[-2,-2,-2])
print(arr[-1,1,-1])

5
9
2
12


In [63]:
import numpy as np
arr=np.array([1,2,3,4,5]) # 1 dimential
print(arr[:3])
print(arr[1:3])
print(arr[0:5:2])
print(arr[0:4:2])
print(arr[-3:-1])
print(arr[-3:-1:-1])

[1 2 3]
[2 3]
[1 3 5]
[1 3]
[3 4]
[]


In [45]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,:3])

[6 7 8]


In [52]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[:1,:3])
print(arr[1,3])
print(arr[1::])
print(arr[1:])

[[1 2 3]]
9
[[ 6  7  8  9 10]]
[[ 6  7  8  9 10]]


In [64]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3 dimential
print(arr[0,:1,:1])  # slicing number == dimention
print(arr[:1,:1,:1])
print(arr[1,1,:1])
print(arr[1,1,:2])
print(arr[0:2,0:2,0:2])

[[1]]
[[[1]]]
[10]
[10 11]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [65]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr.shape)

(2, 2, 3)


In [66]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [68]:
arr=np.array([1,2,3,4,5]) # 1 dimential
print(arr.shape)

(5,)


In [73]:
arr=np.array([1,2,3,4,5],ndmin=5) #  dimential can be modify by 'ndimin'
print(arr)
print(arr.shape)
# [[[[[1 2 3 4 5]]]]]
# -------------------
#        1
#  -----------------
#        1
#   --------------
#        1
#    ------------
#        1
#     ---------
#        5

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [78]:
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(2,3)   # shape can be modify by reshape
print(new)

[[1 2 3]
 [4 5 6]]


In [79]:
arr=np.array([1,2,3,4,5])
new=arr.reshape(2,3)
print(new)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [83]:
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(3,2)
print(new)
print(new.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [82]:
arr=np.array([1,2,3,4,5,6])
new=arr.reshape(2,3,1)
print(new)
print(new.ndim)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3
